### ISSUE TITLE
make it a package

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/synAnnotationUtils#1]

**Comment by kkdang** [comment]
- [ ] add docs to readme
- [ ] shorten module names and organize code around consistent modules

**Comment by kdaily** [comment]
Think we can close this? @teslajoy @xindiguo

**Comment by teslajoy** [comment]
Aye!

**Comment by teslajoy** [comment]
Integrating updated functionality with to https://github.com/Sage-Bionetworks/annotator repo. 
summary of integrated functionality consensus is documented here:  https://docs.google.com/spreadsheets/d/1yTdZE5giDevcQRmDR0tFsxCmtmfsVrrdjAM81rsnXcg/edit#gid=0
