### ISSUE TITLE
add ability to write out a blank manifest, taking in one or more schemas.

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/synAnnotationUtils#16]

**Comment by sgosline** [comment]
I believe @xindiguo  can already do this - does it work for table schema dictionaries as well as jsons?  If so should we add that in and close this?

**Comment by kkdang** [comment]
@xindiguo Please submit a pull request to this repo when ready for review.

**Comment by teslajoy** [comment]
annotation UI will be the user friendly version of this task.
