### ISSUE TITLE
all annotation changes to use CSV uploads.

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/synAnnotationUtils#19]
Currently commands use annotation queries and set-annotations. Annotation queries will go away. All updates to annotations should create csv-format data that can be uploaded to a table view. No more calls to set-annotations.

**Comment by teslajoy** [comment]
syn python client functions to create or upload a file view needs to be implemented. 
Restful API exists: 
https://sagebionetworks.jira.com/wiki/display/PLFM/File+Views

**Comment by teslajoy** [comment]
current file-view jira wiki, calls to an old version of  REAST api synapse docs. 

most updated version html start tag is  docs.synapse.org. via: 
http://docs.synapse.org/rest/index.html

**Comment by teslajoy** [comment]
file/entity view (of type project or file) may be updated via https://github.com/Sage-Bionetworks/synAnnotationUtils/blob/master/synAnnotationUtils/update.py
