### ISSUE TITLE
annotation queries against file views

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/synAnnotationUtils#20]
All uses of select * from file where x=y that pull things down by annotations need to change to pull from the relevant file view entity.

**Comment by teslajoy** [comment]
Currently file view file entity synId retrieval only works if the file view and its associated schema exists (i.e. Schema class doesn't take a file view synId as a parameter). Also, still need to iter over all files individually to update their associated annotation. After parallelization we can change the code to update a chunk at once.

**Comment by teslajoy** [comment]
can pass a sql clause as value see https://github.com/Sage-Bionetworks/synAnnotationUtils/blob/master/synAnnotationUtils/update.py
