### ISSUE TITLE
expand sampleID lists of a file view and associate each to its annotation schema value  

### ISSUE THREAD

**Issue by teslajoy** [Sage-Bionetworks/synAnnotationUtils#28]
sample ids X schema 
Ben's annot utility request 
Larsson has helper code 
example file view as input has been requested.

**Comment by kdaily** [comment]
Don't understand the use case - can you give a minimal reproducible example, please?

**Comment by teslajoy** [comment]
@kdaily This use-case is probably deprecated by us moving from sample id lists separated by comma in a row to meta-data that holds a one-one relation (at least in all of mette's projects).

**Comment by kdaily** [comment]
Great! Closing for now.
