### ISSUE TITLE
Merge repo into synapseAnnotations

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/synAnnotationUtils#29]
After some recent discussion related to organizing the [synapseAnnotations](https://github.com/Sage-Bionetworks/synapseAnnotations) repo, some of us concluded that maintaining two repos for annotation related work is probably redundant. We can merge one git repository into another in a way that preserves file/commit history (check out [this post](https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/) for an example; however, there are a few steps we'd want to take care of to help the process go more smoothly:

1. Get consensus: before doing anything, I want to make sure that everyone on the annotations team is on board with this plan.  
2. Clean up branches in this repo: It's possible to merge individual feature branches, but ideally I would just worry about merging `synAnnotationUtils/master`. That means if anyone has in-progress work in active branches, we should try to get those changes committed and merged.
3. Dry run the merge: I'll fork **synapseAnnotations** and test the process by merging this repo into my (safe) fork. This will provide a reasonable preview of the final result and highlight any potentially problematic steps.
4. Agree on a target time window: Once we have a clear idea of how the merge should proceed, and outstanding changes in this repo have been resolved, it'd be helpful if we could set a time to "freeze" this repo and start the process. I (hopefully) only need an hour or two to get things merged and open a pull request in **synapseAnnotations**.

Anything I've missed? I imagine that @kdaily, @kkdang, @xindiguo, @teslajoy, and @ychae will be the key contributors who will need to coordinate plans on this end.

**Comment by kkdang** [comment]
So at one point, we all concluded that separate repos would be better, I think because we wanted to facilitate use of annotationsUtils as a package that users would install.

Let's make sure we are certain about undoing our previous decision before we do it.

**Comment by sgosline** [comment]
I never understood the previous decision - but I think downloading a few extra jsons with a package is not the end of the world and will make it easier to encourage use.

**Comment by jaeddy** [comment]
@kkdang see discussion [here](https://github.com/Sage-Bionetworks/synapseAnnotations/issues/71).

And yeah, re: step (1) in my list &mdash; definitely won't do anything until we're all on the same page.

**Comment by kdaily** [comment]
Seems that we're all ok with maintaining two separate packages. I think the usage is defined separately enough now to go ahead with that. Recommending closing, won't fix.
