### ISSUE TITLE
add facility to search existing dictionaries

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/synAnnotationUtils#30]
Use case:
A user wants to create a new project-specific dictionary. How can they easily tell what annotations terms already exist? Do their proposed terms overlap with other dictionaries?

**Comment by amapeters** [comment]
I would like to see a synapse table with all key-value terms, descriptions and which json file they are in. It is getting difficult to determine what is currently in place

**Comment by teslajoy** [comment]
Annotations table (syn10005388) and annotation UI
