### ISSUE TITLE
Would like to be able to accommodate annotating all contents of a folder 

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synAnnotationUtils#31]
If a user puts a synapse ID or folder inside the manifest, the values of the manifest should be applied across files in the folder.

**Comment by teslajoy** [comment]
@xindiguo wrote the awesome sync manifest function see: https://github.com/Sage-Bionetworks/synAnnotationUtils/blob/master/bin/sync_manifest.py
