### ISSUE TITLE
entity-view update synapse and row indices error

### ISSUE THREAD

**Issue by teslajoy** [Sage-Bionetworks/synAnnotationUtils#39]
I have two "main" functions for updating and expanding fields utilizing an existing entity-view on my branch (teslajoy-update) in synAnnotationUtils.  

Main function 

  updateEntityView(syn, syn_id, path, clause=None) 

Integration Test function 

 test_update_entityview()
 
Inside _checkSave() I call to drop synapse minimal function and essentially only keep 'etag' of each row to handle the row match. If I leave ROW_ID and ROW_VERSION columns, I get this error: 

"because it is necessary for version tracking in Synapse's tables").format(col_name) )
SynapseError: A column named 'ROW_ID' already exists and does not match the 'ROW_ID' values present in the DataFrame's row names. Please refain from using or modifying 'ROW_ID' as a column for your data because it is necessary for version tracking in Synapse's tables

**Comment by kdaily** [comment]
Close this one @teslajoy?

**Comment by teslajoy** [comment]
yup :)
