### ISSUE TITLE
Create markdown documentation for each command

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synAnnotationUtils#42]
If you write a script please put markdown in docs.

**Comment by sgosline** [comment]
Example is here by @xindiguo : https://github.com/Sage-Bionetworks/synAnnotationUtils/blob/develop/docs/sync_manifest.md

**Comment by kdaily** [comment]
Thought we had discussed using Sphinx (or some other Python docstring friendly tool)?

**Comment by jaeddy** [comment]
I think Sphinx and Markdown can coexist in the docs for a project: you'd still want Sphinx-style docstrings within classes and functions to enable things like `autodoc` and integration with ReadTheDocs (or similar sites), but Markdown could be more friendly for building out doc pages than RST (the default for Sphinx/ReadTheDocs). Relevant link here: http://www.sphinx-doc.org/en/stable/markdown.html

**Comment by kdaily** [comment]
I'm sold!

**Comment by kdaily** [comment]
Closing.
